LIBRARY_LANGUAGES = [
  ["ASL", "American Sign Language (ASL)", "eng&clang=ase"],
  ["Indonesian", "Bahasa Indonesia (Indonesian)", "ind"],
  ["Danish", "Dansk (Danish)", "dan"],
  ["German", "Deutsch (German)", "deu"],
  ["English", "English", "eng"],
  ["Spanish", "Español", "spa"],
  ["Tongan", "Faka-tonga (Tongan)", "ton"],
  ["French", "Français", "fra"],
  ["Samoan", "Gagana Samoa (Samoan)", "smo"],
  ["Italian", "Italiano (Italian)", "ita"],
  ["Hungarian", "Magyar (Hungarian)", "hun"],
  ["Dutch", "Nederlands (Dutch)", "nld"],
  ["Norwegian", "Norsk (Norwegian)", "nor"],
  ["Portuguese", "Português", "por"],
  ["Finnish", "Suomi (Finnish)", "fin"],
  ["Swedish", "Svenska (Swedish)", "swe"],
  ["Russian", "Русский (Russian)", "rus"],
  ["Ukrainian", "Українська (Ukrainian)", "ukr"],
  ["Thai", "ภาษาไทย (Thai)", "tha"],
  ["Korean", "한국어 (Korean)", "kor"],
  ["Chinese", "中文 (Chinese)", "zho"],
  ["Japanese", "日本語 (Japanese)", "jpn"],
  ["Music", "Music", ""],
]
